### ISSUE TITLE
About using OSTree on Nitrux OS.

### ISSUE THREAD

**Issue by luis-lavaire** [nomad-desktop/nitrux-ostree#1]
@star-buck 
@nomad-desktop/software-team 

I finally managed to get `ostree` to build filesystem trees that can be able to boot. After a couple months using it I have some concerns about implementing in our system; which I detail here.

From the `ostree` [online documentation](https://ostree.readthedocs.io/en/latest/), these are the notable features of the tool that we could benefit from:

- Transactional upgrades and rollback for the system.
- Replicating content incrementally over HTTP via GPG signatures and "pinned TLS" support.
- Support for parallel installing more than just 2 bootable roots.
- Binary history on the server side (and client).

...

Nevertheless, there are some drawbacks and concerns that I have about using `ostree` as the next way of distributing our OS.

`ostree` [imposes changes](https://ostree.readthedocs.io/en/latest/manual/adapting-existing/) to critical parts of the filesystem. This changes should't be impossed. In any case, they should just be proposed or suggested. Huge efforts need to be made to customize the system to make it "fit" with `ostree`.
The complexity of this tool is also unjustifiable to perform tasks that are trivial. There's no real need of all those bells and whistles. The fact that "it works" shouldn't be taken as an implication that it does everything well. Simple architectures lead to maintainable, more secure software which has less chances of having bugs (see "[the UNIX philosophy](https://en.m.wikipedia.org/wiki/Unix_philosophy)" for a more detailed explanation of this point), and `ostree` is not simple in any way. Almost all (or all) of the advantages that `ostree` claims over traditional ways of distributing OSs can be achieved with a small set of tools.
I also feel that `ostree` is an incomplete solution because  -- even when it makes drastic changes on the filesystem layout -- it doesn't manage the code needed for booting the deployed OS (this includes bootloader configuration and initramfs procedures). The task is left to the `ostree` users (and this is not for the sake of being more flexible).

`ostree` also doesn't fit so well with our system on which we are using the AppImage format for distributing applications. In fact, `ostree` is the reason for which we are not using the Flatpak format for distributing applications: for it's complexity! Complexity doesn't do anyone any good.

If we choose to use `ostree`, we are going to work more on it rather than our own software or than improving the OS user experience. `ostree` "works", but I can't guarantee it to be the best implementation for the goals it proposes.

In summary, for the sake of our project, I want to recommend the use of a simpler and cleaner solution that won't interfere with our current workflow as `ostree` would do (this simply means refactoring lots of packages so they fit the new filesystem layout and limitations). [znx](https://github.com/nglx/znx) is a tool (just in theory for now) that can achieve `ostree`'s ideals, but in a better way. Don't confuse "simplicity" with "lack of power", "poor performance" or "badly implemented standards" and so on. On the contrary, smaller tools that "[do one thing, and do it well](https://en.m.wikipedia.org/wiki/Unix_philosophy#Do_One_Thing_and_Do_It_Well)", are the building blocks for bigger, complex structures. Right now I've just worked on the concepts and the underlying technologies that could support it. The idea would be very similar to [this one](https://github.com/probonopd/SystemImageKit), but more integrated with the system, allowing updates to be performed. The necessary tools would be:

- `zsync2`
- `GRUB2`
- The ISO filesystem.
- The squash filesystem.
- The overlay filesystem.

Being complemented by:

- Symlinks on the filesystem.
- Proper bootloader configuration.

With the aforementioned tools and methods it would be possible to:

- Perform safe (atomic) updates to any of the systems installed, allowing rollbacks.
- Differential updates (download only the new or modified content).
- Support for multiple OS installations within the same filesystem.
- Download an OS, let `znx` register it and it will be available in the next boot (very similar to AppImage).
- **Simplification of the filesystem layout**.
- **Being transparent to the user (he controls what happens in his system)**.

And all this functionality can be implemented in something as simple as a shell script! This also has great benefits for distro developers (as us), because this mechanism doesn't impose changes to be made. All it needs to work is bootable ISO images (which almost every distro today build). This, IMHO, fits a lot more with the concept of "portable applications" that we have already choose to use with the AppImage format. The next step is filesystem encapsulation. Also, the environment would be really predictable by mixing containerized OSs and AppImages, which is, for people like us (devs), a great advantage. The idea is simple but would greatly change the way things are done in Linux.

I am committed to create a better Linux for the desktop, and I know we all are. One that is open, that gives the user the control of his data, that is transparent in the way of how it does its job.

I really want us all to consider the implications of choosing any tool. We can make something great for people, so lets do our best to achieve it!

**Comment by UriHerrera** [comment]
> I finally managed to get ostree to build filesystem trees that can be able to boot. After a couple months using it I have some concerns about implementing in our system; which I detail here.

Awesome!.

> ostree also doesn't fit so well with our system on which we are using the AppImage format for distributing applications. In fact, ostree is the reason for which we are not using the Flatpak format for distributing applications: for it's complexity! Complexity doesn't do anyone any good.

Yep. A simpler system means less time fixing it and more time improving it.

>  znx is a tool (just in theory for now) that can achieve ostree's ideals, but in a better way. Don't confuse "simplicity" with "lack of power", "poor performance" or "badly implemented standards" and so on. On the contrary, smaller tools that "do one thing, and do it well", are the building blocks for bigger, complex structures.

I like how SystemImageKit works and seeing as there's room for improvement I like the sound of znx. It's also have to do with something I'd like to add to this discussion.

> And all this functionality can be implemented in something as simple as a shell script! This also has great benefits for distro developers (as us), because this mechanism doesn't impose changes to be made. All it needs to work is bootable ISO images (which almost every distro today build).

This.

---

When I was setting up a PC I decided to use Android instead of desktop Linux. When I got into the process of installing Android I noticed the simple way — in retrospective — that it's to install and upgrade this OS.

The way Android-x86 is "installed" to a PC is the following:
* Download ISO (also works as a Live system).
* Run the Installer which does the following:
  * Creates a partition (FAT or ext)
  * Decompresses various `.img` files for different purposes and adds the kernel:
     * `system.img` — Android system.
     * `initrd.img` —  Initial RAM file system.
     * `ramdisk.img` — RAM file system.
     * `data.img` — Contains all application-specific and user-specific data.
     * `kernel` — Android kernel.
  * Installs GRUB.

And that's it. 

Installing in this case doesn't mean a drive with lots of files and folders like _traditional_ systems. Instead it only uses 5 files. 

Better yet how does it get updated?: Android (vanilla) doesn't have this feature built-in but it's only a matter of overwriting `system.img` effectively updating the entire OS in one go. 

---

With Nitrux can follow a similar procedure (installing Nitrux 1st time):
* Download ISO.
* Calamares creates a partition A (same size as ISO) and copies the ISO to the drive.
* Calamares creates a partition B for user data (/home).
* Sets GRUB to boot the ISO in partition A and mount partition B.

So let's assume we're already running Nitrux, how do we update to a new version of the OS?. We can update [Software Updater](https://github.com/nomad-desktop/nx-software-updater) to do the following:
* Compress current ISO in partition A with `tar` and `gzip`. To use as backup or for a rollback function.
* Download new ISO zsync file.
* Check for differences and update the ISO in partition A.
* Reboots.
* GRUB boots new ISO.

The entire system can be created and deployed with znx.

**Comment by star-buck** [comment]
If both you and @UriHerrera think that this is worth a try-out, let's do this.

**Comment by probonopd** [comment]
Actually - I have been using systems with atomic updates for years as my main workstations - using Live ISOs from different distributions and [SystemImageKit](https://github.com/probonopd/SystemImageKit) - without ever unpacking the contents of the Live ISOs... system updates can be done with `zsync` (and heck, even using AppImageUpdate...). If we would "polish" the user experience a bit, then it could for sure make for a nice system.

**Comment by luis-lavaire** [comment]
Development is now here: https://github.com/luis-lavaire/znx
